version: "3.1"
services:
  app:
    restart: always
    container_name: "app"
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080" # When you use HTTP
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  db:
    restart: always
    image: "mysql:5.7.10"
    container_name: "db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    networks:
      - backend
    volumes:
      - mysql-db:/data/db

networks:
  backend:
    driver: bridge
# Names our volume
volumes:
  mysql-db:
